#!/bin/bash

# Apply Compliance Automation Migration
# This script helps apply the migration to your Supabase database

echo "=== COMPLIANCE AUTOMATION MIGRATION ==="
echo ""
echo "⚠️  IMPORTANT: You must apply this migration in your Supabase SQL Editor"
echo ""
echo "Steps:"
echo "1. Open your Supabase dashboard: https://supabase.com/dashboard"
echo "2. Navigate to: SQL Editor"
echo "3. Click: New Query"
echo "4. Copy the migration file contents:"
echo ""
echo "   File: supabase/migrations/20241102_compliance_automation.sql"
echo ""
echo "5. Paste into SQL Editor"
echo "6. Click: Run"
echo "7. Wait for completion (~30-60 seconds)"
echo ""
echo "Expected output:"
echo "  ✅ CREATE TABLE compliance_requirements"
echo "  ✅ CREATE TABLE org_compliance_assets"
echo "  ✅ CREATE TABLE compliance_rules"
echo "  ✅ INSERT 18 rows into compliance_rules"
echo "  ✅ CREATE FUNCTION calculate_compliance_risk_score"
echo "  ✅ CREATE TRIGGER update_compliance_risk_score_trigger"
echo ""
echo "After migration completes, run:"
echo "  npx tsx scripts/extract-compliance-requirements.ts"
echo ""
echo "Or use Supabase CLI (if installed):"
echo "  supabase db push"
echo ""
