-- Create freelancer_invoices table for invoice generation
CREATE TABLE IF NOT EXISTS freelancer_invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_number TEXT NOT NULL UNIQUE,
  freelancer_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  client_id UUID NOT NULL REFERENCES freelancer_clients(id) ON DELETE CASCADE,

  -- Invoice details
  issue_date DATE NOT NULL,
  due_date DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'paid', 'overdue', 'cancelled')),

  -- Amounts
  subtotal DECIMAL(10,2) NOT NULL,
  tax_rate DECIMAL(5,2) DEFAULT 0,
  tax_amount DECIMAL(10,2) DEFAULT 0,
  total_amount DECIMAL(10,2) NOT NULL,

  -- Payment info
  paid_amount DECIMAL(10,2) DEFAULT 0,
  paid_at TIMESTAMPTZ,

  -- Notes
  notes TEXT,

  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add indexes for common queries
CREATE INDEX IF NOT EXISTS idx_invoices_freelancer_user
  ON freelancer_invoices(freelancer_user_id);
CREATE INDEX IF NOT EXISTS idx_invoices_client
  ON freelancer_invoices(client_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status
  ON freelancer_invoices(status);
CREATE INDEX IF NOT EXISTS idx_invoices_issue_date
  ON freelancer_invoices(issue_date DESC);

-- Enable RLS
ALTER TABLE freelancer_invoices ENABLE ROW LEVEL SECURITY;

-- Policy: Freelancers can manage their own invoices
DROP POLICY IF EXISTS "freelancers manage own invoices" ON freelancer_invoices;
CREATE POLICY "freelancers manage own invoices"
  ON freelancer_invoices
  FOR ALL
  USING (auth.uid() = freelancer_user_id)
  WITH CHECK (auth.uid() = freelancer_user_id);

-- Add comments for documentation
COMMENT ON TABLE freelancer_invoices IS 'Invoices generated by freelancers for their clients';
COMMENT ON COLUMN freelancer_invoices.invoice_number IS 'Unique invoice number (e.g., INV-2024-001)';
COMMENT ON COLUMN freelancer_invoices.tax_rate IS 'Tax rate as percentage (e.g., 8.5 for 8.5%)';

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_freelancer_invoices_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update updated_at
DROP TRIGGER IF EXISTS set_freelancer_invoices_updated_at ON freelancer_invoices;
CREATE TRIGGER set_freelancer_invoices_updated_at
  BEFORE UPDATE ON freelancer_invoices
  FOR EACH ROW
  EXECUTE FUNCTION update_freelancer_invoices_updated_at();

-- Function to generate next invoice number
CREATE OR REPLACE FUNCTION generate_invoice_number(user_id UUID)
RETURNS TEXT AS $$
DECLARE
  year TEXT;
  count INT;
  next_num TEXT;
BEGIN
  year := TO_CHAR(NOW(), 'YYYY');

  -- Get count of invoices for this year and user
  SELECT COUNT(*) INTO count
  FROM freelancer_invoices
  WHERE freelancer_user_id = user_id
    AND EXTRACT(YEAR FROM issue_date) = EXTRACT(YEAR FROM NOW());

  -- Generate number with padding
  next_num := LPAD((count + 1)::TEXT, 4, '0');

  RETURN 'INV-' || year || '-' || next_num;
END;
$$ LANGUAGE plpgsql;

-- Update the time_entries table to add invoice_id foreign key if not exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'freelancer_time_entries_invoice_id_fkey'
    AND table_name = 'freelancer_time_entries'
  ) THEN
    ALTER TABLE freelancer_time_entries
      ADD CONSTRAINT freelancer_time_entries_invoice_id_fkey
      FOREIGN KEY (invoice_id) REFERENCES freelancer_invoices(id) ON DELETE SET NULL;
  END IF;
END $$;
